# Generated by Django 3.1.6 on 2021-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210210_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_phone', models.CharField(max_length=255)),
                ('store_email', models.EmailField(max_length=255)),
                ('store_address', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'sys_info',
            },
        ),
    ]
